import crypto from 'crypto';

export class KeyAuth {
  constructor(name, ownerid, secret) {
    this.name = name;
    this.ownerid = ownerid;
    this.secret = secret;
    this.apiUrl = 'https://keyauth.win/api/seller/';
    this.sessionId = null;
  }

  // Inicializar sesión
  async init() {
    try {
      const response = await fetch(this.apiUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          sellerkey: this.secret,
          type: 'init',
          name: this.name,
          ownerid: this.ownerid
        })
      });

      const data = await response.json();
      
      if (data.success) {
        this.sessionId = data.sessionid;
        console.log('✅ KeyAuth session inicializada');
        return true;
      } else {
        console.error('❌ Error init KeyAuth:', data.message);
        return false;
      }
    } catch (error) {
      console.error('❌ Error conexión KeyAuth:', error);
      return false;
    }
  }

  // Crear una key
  async createKey(days, quantity = 1, level = 1, note = '') {
    try {
      // Inicializar sesión si no existe
      if (!this.sessionId) {
        const initialized = await this.init();
        if (!initialized) {
          throw new Error('No se pudo inicializar KeyAuth');
        }
      }

      const response = await fetch(this.apiUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          sellerkey: this.secret,
          type: 'add',
          format: 'JSON',
          expiry: days.toString(),
          mask: 'XXXX-XXXX-XXXX-XXXX',
          level: level.toString(),
          amount: quantity.toString(),
          owner: this.ownerid,
          character: '2', // Números y letras
          note: note || `Generated by Aura Hax Bot - ${days} days`
        })
      });

      const data = await response.json();

      if (data.success) {
        console.log(`✅ Key generada: ${data.key}`);
        return data.key;
      } else {
        console.error('❌ Error al generar key:', data.message);
        throw new Error(data.message);
      }
    } catch (error) {
      console.error('❌ Error al crear key:', error);
      throw error;
    }
  }

  // Verificar una key
  async verifyKey(key) {
    try {
      if (!this.sessionId) {
        await this.init();
      }

      const response = await fetch(this.apiUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          sellerkey: this.secret,
          type: 'verify',
          key: key,
          owner: this.ownerid
        })
      });

      const data = await response.json();
      return data.success;
    } catch (error) {
      console.error('Error al verificar key:', error);
      return false;
    }
  }

  // Eliminar una key
  async deleteKey(key) {
    try {
      if (!this.sessionId) {
        await this.init();
      }

      const response = await fetch(this.apiUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          sellerkey: this.secret,
          type: 'del',
          key: key,
          owner: this.ownerid
        })
      });

      const data = await response.json();
      return data.success;
    } catch (error) {
      console.error('Error al eliminar key:', error);
      return false;
    }
  }

  // Obtener info de una key
  async getKeyInfo(key) {
    try {
      if (!this.sessionId) {
        await this.init();
      }

      const response = await fetch(this.apiUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          sellerkey: this.secret,
          type: 'info',
          key: key,
          owner: this.ownerid
        })
      });

      const data = await response.json();
      
      if (data.success) {
        return {
          key: data.key,
          note: data.note,
          expires: data.expires,
          status: data.status,
          level: data.level
        };
      }
      
      return null;
    } catch (error) {
      console.error('Error al obtener info de key:', error);
      return null;
    }
  }
}
